# Naam van de actie
name: 'deploy module container'

#On regelt op welke actie het script activeert
on:
  workflow_dispatch:
    branches:
      - master
    paths:
      - '/packages/container/**'
  push:
    branches:
      - master
    paths:
      - '/packages/container/**'

#Zorg dat de actie wordt uitgevoer relatief in de folder container
defaults:
  run:
    working-directory: /packages/container

#Maak een virtuale machine  (ubuntu)
jobs:
  build:
    runs-on: ubuntu-latest

    # definieer alle stappen
    steps:
      #Checkout lokale repo naar de virtuele machine
      - name: Checkout
        uses: actions/checkout@v2
      
      #Voer uit, npm install (node_modules) en darana het build script
      - run: npm install
      - run: npm run build

      #Voer uit sftp naar deploy server
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USER_NAME }}
          server: ${{ secrets.SSH_SERVER_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './dist/*'
          remote_path: '/mnt/data/tinydeli.nl/httpd.www/container/latest'
          args: '-o ConnectTimeout=5'
